# Generated by Django 5.0.14 on 2026-03-19 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name="O'yinchi ID")),
                ('first_name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiyasi')),
                ('fathers_name', models.CharField(blank=True, max_length=255, verbose_name='Otasining ismi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/', verbose_name='Rasm')),
                ('height', models.FloatField(blank=True, null=True, verbose_name="Bo'yi (sm)")),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Vazni (kg)')),
                ('birthday', models.DateField(verbose_name="Tug'ilgan sana")),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Futbolka raqami')),
                ('position', models.CharField(blank=True, choices=[('GK', 'Darvozabon'), ('DEF', 'Himoyachi'), ('MID', 'Yarim himoyachi'), ('FWD', 'Hujumchi')], max_length=10, verbose_name='Pozitsiya')),
            ],
            options={
                'verbose_name': "O'yinchi",
                'verbose_name_plural': "O'yinchilar",
                'ordering': ['position', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiyasi')),
                ('fathers_name', models.CharField(blank=True, max_length=255, verbose_name='Otasining ismi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='coach_photos/', verbose_name='Rasm')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Murabbiy',
                'verbose_name_plural': 'Murabbiylar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('text', models.TextField(verbose_name='Matn')),
                ('short_text', models.CharField(blank=True, max_length=500, verbose_name='Qisqa matn')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='news_photos/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.news')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(choices=[('passport', 'Pasport'), ('license', 'Litsenziya'), ('medical', 'Tibbiy'), ('other', 'Boshqa')], max_length=50)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.coach')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiyasi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='core.region', verbose_name='Viloyat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='region_admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Viloyat admini',
                'verbose_name_plural': 'Viloyat adminlari',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadiums', to='core.city', verbose_name='Shahar')),
            ],
            options={
                'verbose_name': 'Stadion',
                'verbose_name_plural': 'Stadionlar',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('type', models.CharField(choices=[('olympic', 'Olimpik tizim'), ('round_robin', 'Doiraviy tizim')], max_length=20, verbose_name='Turi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Yakunlangan')),
                ('draw_done', models.BooleanField(default=False, verbose_name="Qur'a tashlangan")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='core.category', verbose_name='Kategoriya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='core.stadium', verbose_name='Stadion')),
            ],
            options={
                'verbose_name': 'Musobaqa',
                'verbose_name_plural': 'Musobaqalar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='Logotip')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.category', verbose_name='Kategoriya')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.city', verbose_name='Shahar')),
                ('coach', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='core.coach', verbose_name='Murabbiy')),
            ],
            options={
                'verbose_name': 'Jamoa',
                'verbose_name_plural': 'Jamoalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiyasi')),
                ('fathers_name', models.CharField(blank=True, max_length=255, verbose_name='Otasining ismi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_request_photos/', verbose_name='Rasm')),
                ('height', models.FloatField(blank=True, null=True, verbose_name="Bo'yi (sm)")),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Vazni (kg)')),
                ('birthday', models.DateField(verbose_name="Tug'ilgan sana")),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Futbolka raqami')),
                ('position', models.CharField(blank=True, choices=[('GK', 'Darvozabon'), ('DEF', 'Himoyachi'), ('MID', 'Yarim himoyachi'), ('FWD', 'Hujumchi')], max_length=10, verbose_name='Pozitsiya')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holati')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_requests', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi (Coach)')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='core.player', verbose_name="Yaratilgan o'yinchi")),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_requests', to='core.team', verbose_name='Jamoa')),
            ],
            options={
                'verbose_name': "O'yinchi so'rovi",
                'verbose_name_plural': "O'yinchi so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team', verbose_name='Jamoa'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_home', models.PositiveIntegerField(blank=True, null=True)),
                ('score_away', models.PositiveIntegerField(blank=True, null=True)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_bye', models.BooleanField(default=False)),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.competition')),
                ('team_away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team')),
                ('team_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team')),
            ],
            options={
                'verbose_name': "O'yin",
                'verbose_name_plural': "O'yinlar",
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='core.team', verbose_name='Jamoalar'),
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='core.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='core.player')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='core.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
